spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=erp;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Th\u01B0 m\u1EE5c ch\u1EE9a \u1EA3nh
upload.folder=uploads

# Cho phép Spring ph\u1EE5c v\u1EE5 file t\u0129nh t\u1EEB th\u01B0 m\u1EE5c 'uploads'
spring.web.resources.static-locations=file:uploads/
