# C\u1EA5u hình k\u1EBFt n\u1ED1i SQL Server v\u1EDBi h\u1ED7 tr\u1EE3 Unicode
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=erp;encrypt=true;trustServerCertificate=true;useUnicode=true;characterEncoding=UTF-8
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.connection.charSet=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.connection.characterEncoding=utf8

# Thi\u1EBFt l\u1EADp encoding cho toàn \u1EE9ng d\u1EE5ng web
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

#
upload.folder=D:/uploads/product